DEFAULT_USERNAME = "Usuário"
DEFAULT_AUTH_PORT = 20556
DEFAULT_COMM_PORT = 20557
ED25519_CHANNELS = ["bravo", "hotel", "tango"]

DEFAULT_CLIENT_RSA_TIMEOUT = 20  
DEFAULT_CLIENT_PASSWORD_RESPONSE_TIMEOUT = 5  
DEFAULT_CLIENT_MESSAGE_RECEIVE_TIMEOUT = 1  
DEFAULT_CLIENT_HANDSHAKE_TIMEOUT = 5  
DEFAULT_HOST_UDP_OPERATION_TIMEOUT = 5  
DEFAULT_HOST_CLIENT_DATA_RECEIVE_TIMEOUT = 5 